name: GKuber CI/CD


on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
  workflow_dispatch: # to manually run this workflow


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gkuber:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/gkuber:latest

      - name: Deploy on Lightsail
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            mkdir -p ~/gkuber
            cd ~/gkuber
            [ -f docker-compose.yml ] || exit 1
            docker pull ${{ secrets.DOCKER_USERNAME }}/gkuber:latest
            docker compose down || true
            docker compose up -d


